In [45]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import eigh

Given the moment of Inertia Tensor of the form: 

$\begin{bmatrix}
\sum_{i=1}^{N} (y_i^2+z_i^2)m_i & -\sum_{i=1}^{N} x_i y_i m_i & -\sum_{i=1}^{N}x_i z_i m_i \\
-\sum_{i=1}^{N}x_i y_i m_i  &  \sum_{i=1}^{N} (x_i^2+z_i^2)m_i& -\sum_{i=1}^{N}z_i y_i m_i\\
-\sum_{i=1}^{N}z_i x_i m_i& -\sum_{i=1}^{N}z_i y_i m_i& \sum_{i=1}^{N}(x_i^2+y_i^2)m_i
\end{bmatrix}$

Creating a general class to calaculate the moment of inertia of any object

In [55]:
class InertiaTensor:
    def __init__(self,image,mass=1,normalize=False ):
        
        self.norm= normalize
        self.coordinates = image#np.loadtxt(image,unpack=True) 
        if self.norm==True:
            self.coordinates/= max(self.coordinates.ravel()) 
        self.x , self.y ,self.z = self.coordinates[:,0],self.coordinates[:,1],self.coordinates[:,2]
        self.n = len(self.x)
        self.m=mass#/self.n
        
    
    def object(self):
        self.fig = plt.figure()
        self.ax = self.fig.add_subplot(projection='3d')
        self.ax.set_xlabel('x Coordinates')
        self.ax.set_ylabel('y Coordinates')
        self.ax.set_zlabel('z Coordinates')
        return self.ax.scatter(self.x,self.y,self.z)
    def continous(self):
        self.ixy= -np.sum(np.dot(self.x,self.y)*self.m)/self.n
        self.ixz= -np.sum(np.dot(self.x,self.z)*self.m)/self.n
        self.iyz= -np.sum(np.dot(self.z,self.y)*self.m)/self.n
        self.ixx= np.sum((self.x**2 +self.y**2)*self.m)/self.n
        self.iyy= np.sum((self.x**2 +self.z**2)*self.m)/self.n
        self.izz= np.sum((self.z**2 +self.y**2)*self.m)/self.n
        self.inertia= np.array([[self.ixx,self.ixy,self.ixz],
        [self.ixy,self.iyy,self.iyz],[self.ixz,self.iyz,self.izz]])
        return self.inertia
    def discrete(self):
        return self.n*self.continous()
    def principle(self,text):
        if text=='continous':
            values,vectors=np.linalg.eigh(self.continous())
            print('The principle moments are',values)
            return self.ax.plot(np.zeros(3),vectors.T[0,:])

            
      

    

In [30]:
sph= InertiaTensor(sphere)
sph.continous()


array([[ 1.95827487e+01, -1.79254577e-18, -3.83156658e-17],
       [-1.79254577e-18,  1.95827487e+01, -1.11137838e-16],
       [-3.83156658e-17, -1.11137838e-16,  1.95827487e+01]])

In [56]:
mass=np.array([4.4,1.2,3.5,7.1])
position=np.array([[0.7,0,2*0.7],[2*0.7,2*0.7,2*0.7],[0.7,0.7,0],[2*0.7,2*0.7,0]])
tensor=InertiaTensor(position,mass)
print(tensor.discrete())
values,vectors=np.linalg.eigh(tensor.discrete())
print("The principle moments of inertia is,",values)
print('The principle axis as column vectors are \n',vectors.T)

[[ 38.122 -71.442 -47.628]
 [-71.442  31.115 -31.752]
 [-47.628 -31.752  28.959]]
The principle moments of inertia is, [-69.02646931  58.36372283 108.85874648]
The principle axis as column vectors are 
 [[ 0.62331489  0.60266635  0.49826882]
 [ 0.17936542  0.51001714 -0.84125535]
 [ 0.76112193 -0.61373918 -0.20980378]]


In [57]:
n=30
a= np.linspace(0,1,30)
x,y,z = np.meshgrid(a,a,a)

cubepoints = np.array([x.ravel(),y.ravel(),z.ravel()]).T
cube=InertiaTensor(cubepoints)

print(cube.continous())
values,vectors=np.linalg.eigh(cube.continous())
print("The principle moments of inertia is,",values)
print('The principle axis as column vectors are \n',vectors.T)


[[ 0.67816092 -0.25       -0.25      ]
 [-0.25        0.67816092 -0.25      ]
 [-0.25       -0.25        0.67816092]]
The principle moments of inertia is, [0.17816092 0.92816092 0.92816092]
The principle axis as column vectors are 
 [[ 0.57735027  0.57735027  0.57735027]
 [-0.81649658  0.40824829  0.40824829]
 [ 0.         -0.70710678  0.70710678]]
